from .auth import router as auth_router
from .dashboard import router as dashboard_router
from .ventas_perdidas import router as ventas_perdidas_router
from .items import router as items_router
from .auditoria import router as auditoria_router
from .cierres import router as cierres_router
from .tareas import router as tareas_router
from .ajustes_stock import router as ajustes_stock_router
from .pedidosya import router as pedidosya_router
from .vencimientos import router as vencimientos_router
from .recontactos import router as recontactos_router
# Rutas para BD Anexa (mi_sucursal)
from .sugerencias import router as sugerencias_router
from .descargos import router as descargos_router
from .auditoria_mensual import router as auditoria_mensual_router
from .facturas import router as facturas_router
from .conteo_stock import router as conteo_stock_router
from .tareas_resumen import router as tareas_resumen_router
